use_frameworks!

target 'CreativeDatasource_Example' do
  pod 'CreativeDatasource', :path => '../'

  target 'CreativeDatasource_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
