use_frameworks!

target 'ReactiveListDatasource_Example' do
  pod 'ReactiveListDatasource', :path => '../'

  target 'ReactiveListDatasource_Tests' do
    inherit! :search_paths

    # pod 'Quick', '~> 1.2.0'
    # pod 'Nimble', '~> 7.0.2'
  end
end
